image: node:18.16.0

variables:
  CODE_PATH: main/app/quasar-project

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - ${CODE_PATH}/node_modules/

check-merge_request:
  script:
    - "echo build:check-mr: checking that title is valid ..."
    - 'echo $CI_MERGE_REQUEST_TITLE|grep -P "^([dD]raft:\s)?(ci|docs|feat|fix|perf|refactor|style|test)(?:\(([\w\$\.\-\*\s]*)\))?\:\s(.{1,50})$" || exit 10'
    - "echo build:check-mr: checking that assignee is valid ..."
    - '[ -z "$CI_MERGE_REQUEST_ASSIGNEES" ] && exit 10 || exit 0'
  tags: [front]
  only:
    refs:
      - merge_requests

testapp:
  script:
    - cd ${CODE_PATH}
    - yarn install
    - yarn build
    - echo Linter checking ...
    - yarn lint
    - yarn format:ci
    - echo Typescript checking ...
    - yarn check
    - echo Unit tests checking ...
    - yarn test:unit:ci
  tags: [front]
  only:
    refs:
      - merge_requests

.generate-apk: &generate-apk
  - apt-get --quiet update && apt-get --quiet install --yes grep curl coreutils ca-certificates-java openjdk-17-jre openjdk-17-jdk
  - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
  - mv .secure_files/ayruu-keystore.jks ${CODE_PATH}/src-capacitor/ayruu-keystore.jks
  - mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
  - curl -L https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o cmdline-tools.zip
  - unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
  - rm cmdline-tools.zip
  - $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/bin/sdkmanager --licenses <<< $'y\ny\ny\ny\ny\ny\ny\n'
  - $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "extras;google;m2repository" "extras;android;m2repository"
  - cd ${CODE_PATH}/
  - touch .env .env.mobile.prod
  - echo API_GCP_URL="${API_GCP_URL}" >> .env
  - echo API_GOOGLE_MAPS="${API_GOOGLE_MAPS}" >> .env
  - echo MOBILE_KEY="${MOBILE_KEY}" >> .env
  - echo FIREBASE_APIKEY="${FIREBASE_APIKEY}" >> .env
  - echo FIREBASE_SENDERID="${FIREBASE_SENDERID}" >> .env
  - echo FIREBASE_APPID="${FIREBASE_APPID}" >> .env
  - echo FIREBASE_MEASUREMENTID="${FIREBASE_MEASUREMENTID}" >> .env
  - echo APPSTORE_VALIDATION_EMAIL="${APPSTORE_VALIDATION_EMAIL}" >> .env
  - echo API_CHATBOT="${API_CHATBOT}" >> .env.mobile.prod
  - echo API_CONTRACT="${API_CONTRACT}" >> .env.mobile.prod
  - echo API_ENGINE="${API_ENGINE}" >> .env.mobile.prod
  - echo API_CAR="${API_CAR}" >> .env.mobile.prod
  - echo API_DRIVER="${API_DRIVER}" >> .env.mobile.prod
  - echo API_FLIGHT="${API_FLIGHT}" >> .env.mobile.prod
  - echo API_HOTEL="${API_HOTEL}" >> .env.mobile.prod
  - echo API_TRAIN="${API_TRAIN}" >> .env.mobile.prod
  - echo API_ORGANIZATION="${API_ORGANIZATION}" >> .env.mobile.prod
  - echo API_FEED="${API_FEED}" >> .env.mobile.prod
  - echo API_POLICY="${API_POLICY}" >> .env.mobile.prod
  - echo API_BOOKER_ENGINE_TRAIN="${API_BOOKER_ENGINE_TRAIN}" >> .env.mobile.prod
  - echo API_BOOKER_ENGINE_URL="${API_BOOKER_ENGINE_URL}" >> .env.mobile.prod
  - yarn install
  - cd src-capacitor && yarn install --prod && cd ..
  - |
    if [[ "prod" == "$CI_ENVIRONMENT_NAME" ]] ; then
      yarn build -m capacitor -T android ;
    else 
      yarn build -m capacitor -T android --debug ;
    fi
  - cd src-capacitor/android
  - |
    if [[ "prod" == "$CI_ENVIRONMENT_NAME" ]] ; then
      chmod +x ./gradlew
      ./gradlew :app:bundleRelease ;
      jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore "../ayruu-keystore.jks" -storepass "${KEYSTORE_PASS}" -keypass "${KEYSTORE_PASS}" "./app/build/outputs/bundle/release/app-release.aab" "ayruu" ;
      ./gradlew assembleDebug ;
    fi

apk-debug:
  variables:
    ANDROID_SDK_ROOT: $CI_PROJECT_DIR/android-sdk
    ANDROID_HOME: $CI_PROJECT_DIR/android-sdk
  only:
    refs:
      - merge_requests
  tags: [front]
  script:
    - *generate-apk
  when: manual
  allow_failure: true
  artifacts:
    paths:
      - ${CODE_PATH}/src-capacitor/android/app/build/outputs
    expire_in: 1 week

apk-release: &apk-release
  variables:
    ANDROID_SDK_ROOT: $CI_PROJECT_DIR/android-sdk
    ANDROID_HOME: $CI_PROJECT_DIR/android-sdk
  environment: 
    name: staging
    url: https://staging-app.ayruu.com
  only:
    - tags
  tags: [front]
  script:
    - *generate-apk
    - "curl --header \"PRIVATE-TOKEN: $CI_TOKEN\" --upload-file app/build/outputs/apk/debug/app-debug.apk https://gitlab.ayruu.com/api/v4/projects/$CI_PROJECT_ID/packages/generic/android/$CI_COMMIT_TAG/ayruu-mobile-staging-debug.apk"

apk-release-prod:
  <<: *apk-release
  environment: 
    name: prod
    url: https://app.ayruu.com
  variables:
    ANDROID_SDK_ROOT: $CI_PROJECT_DIR/android-sdk
    ANDROID_HOME: $CI_PROJECT_DIR/android-sdk
  script:
    - *generate-apk
    - "curl --header \"PRIVATE-TOKEN: $CI_TOKEN\" --upload-file app/build/outputs/apk/debug/app-debug.apk https://gitlab.ayruu.com/api/v4/projects/$CI_PROJECT_ID/packages/generic/android/$CI_COMMIT_TAG/ayruu-mobile-prod-debug.apk"
    - "curl --header \"PRIVATE-TOKEN: $CI_TOKEN\" --upload-file app/build/outputs/bundle/release/app-release.aab https://gitlab.ayruu.com/api/v4/projects/$CI_PROJECT_ID/packages/generic/android/$CI_COMMIT_TAG/ayruu-mobile-prod-release.aab"
