version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:21.5.0
    working_directory: ~/motus-game-vuejs

jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  lint:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/motus-game-vuejs
      - run:
          name: Run ESLint
          command: yarn lint

  format:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/motus-game-vuejs
      - run:
          name: Check Code Format
          command: yarn format:ci

  build:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/motus-game-vuejs
      - run:
          name: Build Project
          command: yarn build

  check:
      executor: node-executor
      steps:
        - checkout
        - attach_workspace:
            at: ~/motus-game-vuejs
        - run:
            name: Typescript checking
            command: yarn check

  test:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/motus-game-vuejs
      - run:
          name: Run Unit Tests
          command: yarn test:unit:ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - format:
          requires:
            - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - setup
